### ISSUE TITLE
Plugin is compatible with ST3

### ISSUE THREAD

**Issue by jobedom** [akshaykumar90/sublime-font-cycler#1]
You should update your plugin metadata so it appears as ST3 compatible in Package Control. I've just installed it cloning this Git repo and it works just fine.

**Comment by reagle** [comment]
Yes, I'd like to use this on ST3, so it seems like a small thing to update! If there's no movement,  @Tenebrous or @jobedom, perhaps you would fork it?

**Comment by Tenebrous** [comment]
Done! https://github.com/Tenebrous/sublime-font-cycler

**Comment by akshaykumar90** [comment]
This is fixed now. Thanks @Tenebrous for the pull request.
