### ISSUE TITLE
Add option to set wrap_width

### ISSUE THREAD

**Issue by marcovirtual** [akshaykumar90/sublime-font-cycler#11]
It would be nice to add the ability to also set a different `wrap_width` for each font. Would make this plugin even better. Thank you!

**Comment by marcovirtual** [comment]
I have added the option to `wrap_width` and made a pull request. #12

**Comment by akshaykumar90** [comment]
Can you tell me a bit more about your use-case here?

I would have imagined `wrap_width` as something you need different across different type of files, like python source files vs. markdown documents, etc. Why should it vary with fonts?

**Comment by marcovirtual** [comment]
Hi! This feature is very useful when using proportional width fonts, such as Georgia, Verdana or Roboto, which I usually do when writing prose. 

As Sublime Text calculates the wrap length based on the widest characters (usually `W`), lines with proportional width fonts get too wide for optimal line length, so it's better to reduce `wrap_length` to something around ~40 when using proportional width fonts.

**Comment by akshaykumar90** [comment]
Thanks for the context (and the pull request). Sounds good to me. I have left a small comment on the PR.

**Comment by akshaykumar90** [comment]
Released this in v0.5.0. Should be rolling out soon. Thanks for the suggestion!

**Comment by marcovirtual** [comment]
Thank YOU for your excellent work! Have a good week!
