### ISSUE TITLE
support for changing font size only

### ISSUE THREAD

**Issue by qufighter** [akshaykumar90/sublime-font-cycler#4]
I hacked this script and with the latest update realized I never contributed my patch, but let's discuss.

I changed this line: https://github.com/akshaykumar90/sublime-font-cycler/blob/master/FontCycler.py#L30

To read:

`if fonts_list[index]["font_face"] == current_font_face and fonts_list[index]["font_size"] == current_font_size:
`

So above that I may have defined `current_font_size = settings.get("font_size")`

This works good for me but I'm not sure about all use cases, every font in my list has a size defined.  That may be why I never contributed the patch.  Maybe the new logic should only trigger if `fonts_list[index]["font_size"]` was defend.

Feature: Allow the same font to appear in the font list twice at a different size, and still detect the current index in the font list.

I suppose the problem is why stop there, maybe other properties should key as unique indexes too, identifying the current index is a tricky problem unless there is an easy way to track and increment the setting.

I realize the whole point may be to change font face but I find that zooming in 5+ levels lags my many open editors way too much and reducing this to one keypress was a godsend yielding instant results.  I don't like any other fonts I tried nearly as much as the default one, especially when doubled!

**Comment by akshaykumar90** [comment]
This is a great suggestion. I myself have to bump up font size on different occasions, and if we are able to implement this right, this would be a great addition to the existing feature list. I will look into this.

**Comment by akshaykumar90** [comment]
This should now be fixed (See 85a381d7cc9065d44271957a136408f6c9707e29). New version should be rolling out soon. Let me know if you see some issues with this.
