### ISSUE TITLE
Cycle algo a bit presumptious

### ISSUE THREAD

**Issue by ozra** [akshaykumar90/sublime-font-cycler#9]
I've added the same fonts two times for some, with different size only - because sublime fucks up when I change sizes with ctrl +/- and use font-cycler together for some reason (might be another thing to look into...) - anyway - the cycle algo jumps to the first instance in the hash with the font name, completely ignoring font-size, etc. properties, as part of "identification key" for active choice.

Thanks for a must-have utility btw!

Hope you understand what I mean X-D

**Comment by akshaykumar90** [comment]
Thanks for opening this issue. Should be an easy fix. Will fix this and make a new release.

Glad you like using font-cycler. ^_^

**Comment by akshaykumar90** [comment]
This should now be fixed (See 85a381d). New version should be rolling out soon. Let me know if you see some issues with this.
